-- Auto-generated: update all dish images to local curated photos

UPDATE dishes SET image_url = '/dishes/congee-with-greens.jpg' WHERE dish_name = 'Congee with Greens';
UPDATE dishes SET image_url = '/dishes/steamed-vegetable-buns.jpg' WHERE dish_name = 'Steamed Vegetable Buns';
UPDATE dishes SET image_url = '/dishes/egg-jianbing.jpg' WHERE dish_name = 'Egg Jianbing';
UPDATE dishes SET image_url = '/dishes/chicken-congee.jpg' WHERE dish_name = 'Chicken Congee';
UPDATE dishes SET image_url = '/dishes/mapo-tofu-vegetarian.jpg' WHERE dish_name = 'Mapo Tofu (Vegetarian)';
UPDATE dishes SET image_url = '/dishes/vegetable-fried-rice.jpg' WHERE dish_name = 'Vegetable Fried Rice';
UPDATE dishes SET image_url = '/dishes/kung-pao-chicken.jpg' WHERE dish_name = 'Kung Pao Chicken';
UPDATE dishes SET image_url = '/dishes/sweet-and-sour-pork.jpg' WHERE dish_name = 'Sweet and Sour Pork';
UPDATE dishes SET image_url = '/dishes/buddha-s-delight.jpg' WHERE dish_name = 'Buddha''s Delight';
UPDATE dishes SET image_url = '/dishes/dan-dan-noodles-veg.jpg' WHERE dish_name = 'Dan Dan Noodles (Veg)';
UPDATE dishes SET image_url = '/dishes/peking-duck-pancakes.jpg' WHERE dish_name = 'Peking Duck Pancakes';
UPDATE dishes SET image_url = '/dishes/steamed-whole-fish.jpg' WHERE dish_name = 'Steamed Whole Fish';
UPDATE dishes SET image_url = '/dishes/string-hoppers-with-sambol.jpg' WHERE dish_name = 'String Hoppers with Sambol';
UPDATE dishes SET image_url = '/dishes/coconut-roti.jpg' WHERE dish_name = 'Coconut Roti';
UPDATE dishes SET image_url = '/dishes/egg-hoppers.jpg' WHERE dish_name = 'Egg Hoppers';
UPDATE dishes SET image_url = '/dishes/fish-cutlets.jpg' WHERE dish_name = 'Fish Cutlets';
UPDATE dishes SET image_url = '/dishes/dhal-curry.jpg' WHERE dish_name = 'Dhal Curry';
UPDATE dishes SET image_url = '/dishes/jackfruit-mallung.jpg' WHERE dish_name = 'Jackfruit Mallung';
UPDATE dishes SET image_url = '/dishes/chicken-curry.jpg' WHERE dish_name = 'Chicken Curry';
UPDATE dishes SET image_url = '/dishes/fish-ambul-thiyal.jpg' WHERE dish_name = 'Fish Ambul Thiyal';
UPDATE dishes SET image_url = '/dishes/wambatu-moju.jpg' WHERE dish_name = 'Wambatu Moju';
UPDATE dishes SET image_url = '/dishes/gotu-kola-mallung.jpg' WHERE dish_name = 'Gotu Kola Mallung';
UPDATE dishes SET image_url = '/dishes/lamprais.jpg' WHERE dish_name = 'Lamprais';
UPDATE dishes SET image_url = '/dishes/devilled-prawns.jpg' WHERE dish_name = 'Devilled Prawns';
UPDATE dishes SET image_url = '/dishes/masala-dosa.jpg' WHERE dish_name = 'Masala Dosa';
UPDATE dishes SET image_url = '/dishes/curd-rice.jpg' WHERE dish_name = 'Curd Rice';
UPDATE dishes SET image_url = '/dishes/egg-bhurji.jpg' WHERE dish_name = 'Egg Bhurji';
UPDATE dishes SET image_url = '/dishes/chicken-keema-pav.jpg' WHERE dish_name = 'Chicken Keema Pav';
UPDATE dishes SET image_url = '/dishes/dal-tadka.jpg' WHERE dish_name = 'Dal Tadka';
UPDATE dishes SET image_url = '/dishes/paneer-butter-masala.jpg' WHERE dish_name = 'Paneer Butter Masala';
UPDATE dishes SET image_url = '/dishes/chicken-biryani.jpg' WHERE dish_name = 'Chicken Biryani';
UPDATE dishes SET image_url = '/dishes/fish-curry-coastal.jpg' WHERE dish_name = 'Fish Curry (Coastal)';
UPDATE dishes SET image_url = '/dishes/palak-paneer.jpg' WHERE dish_name = 'Palak Paneer';
UPDATE dishes SET image_url = '/dishes/poha.jpg' WHERE dish_name = 'Poha';
UPDATE dishes SET image_url = '/dishes/vegetable-biryani.jpg' WHERE dish_name = 'Vegetable Biryani';
UPDATE dishes SET image_url = '/dishes/butter-chicken.jpg' WHERE dish_name = 'Butter Chicken';
UPDATE dishes SET image_url = '/dishes/lamb-rogan-josh.jpg' WHERE dish_name = 'Lamb Rogan Josh';
