/** Auto-generated by scripts/download-dish-images.mjs — do not edit by hand. */
export const DISH_IMAGE_PATHS: Record<string, string> = {
  "Congee with Greens": "/dishes/congee-with-greens.jpg",
  "Steamed Vegetable Buns": "/dishes/steamed-vegetable-buns.jpg",
  "Egg Jianbing": "/dishes/egg-jianbing.jpg",
  "Chicken Congee": "/dishes/chicken-congee.jpg",
  "Mapo Tofu (Vegetarian)": "/dishes/mapo-tofu-vegetarian.jpg",
  "Vegetable Fried Rice": "/dishes/vegetable-fried-rice.jpg",
  "Kung Pao Chicken": "/dishes/kung-pao-chicken.jpg",
  "Sweet and Sour Pork": "/dishes/sweet-and-sour-pork.jpg",
  "Buddha's Delight": "/dishes/buddha-s-delight.jpg",
  "Dan Dan Noodles (Veg)": "/dishes/dan-dan-noodles-veg.jpg",
  "Peking Duck Pancakes": "/dishes/peking-duck-pancakes.jpg",
  "Steamed Whole Fish": "/dishes/steamed-whole-fish.jpg",
  "String Hoppers with Sambol": "/dishes/string-hoppers-with-sambol.jpg",
  "Coconut Roti": "/dishes/coconut-roti.jpg",
  "Egg Hoppers": "/dishes/egg-hoppers.jpg",
  "Fish Cutlets": "/dishes/fish-cutlets.jpg",
  "Dhal Curry": "/dishes/dhal-curry.jpg",
  "Jackfruit Mallung": "/dishes/jackfruit-mallung.jpg",
  "Chicken Curry": "/dishes/chicken-curry.jpg",
  "Fish Ambul Thiyal": "/dishes/fish-ambul-thiyal.jpg",
  "Wambatu Moju": "/dishes/wambatu-moju.jpg",
  "Gotu Kola Mallung": "/dishes/gotu-kola-mallung.jpg",
  "Lamprais": "/dishes/lamprais.jpg",
  "Devilled Prawns": "/dishes/devilled-prawns.jpg",
  "Masala Dosa": "/dishes/masala-dosa.jpg",
  "Curd Rice": "/dishes/curd-rice.jpg",
  "Egg Bhurji": "/dishes/egg-bhurji.jpg",
  "Chicken Keema Pav": "/dishes/chicken-keema-pav.jpg",
  "Dal Tadka": "/dishes/dal-tadka.jpg",
  "Paneer Butter Masala": "/dishes/paneer-butter-masala.jpg",
  "Chicken Biryani": "/dishes/chicken-biryani.jpg",
  "Fish Curry (Coastal)": "/dishes/fish-curry-coastal.jpg",
  "Palak Paneer": "/dishes/palak-paneer.jpg",
  "Poha": "/dishes/poha.jpg",
  "Vegetable Biryani": "/dishes/vegetable-biryani.jpg",
  "Butter Chicken": "/dishes/butter-chicken.jpg",
  "Lamb Rogan Josh": "/dishes/lamb-rogan-josh.jpg",
  "Thayir Sadam": "/dishes/curd-rice.jpg",
  "Thayir Saadam": "/dishes/curd-rice.jpg"
};

export function dishImageSlug(dishName: string): string {
  return dishName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export function getLocalDishImagePath(dishName: string): string | undefined {
  if (DISH_IMAGE_PATHS[dishName]) return DISH_IMAGE_PATHS[dishName];
  const slug = dishImageSlug(dishName);
  return DISH_IMAGE_PATHS[Object.keys(DISH_IMAGE_PATHS).find(
    (k) => dishImageSlug(k) === slug,
  ) ?? ""];
}
