import type { Recipe } from "@/types/recipe";

const IMG = {
  chinese:
    "https://images.unsplash.com/photo-1525755662778-989dffb1006f?w=800&q=80",
  indian:
    "https://images.unsplash.com/photo-1585937421612-70a008592f82?w=800&q=80",
  sriLankan:
    "https://images.unsplash.com/photo-1604908176997-43162f4d978e?w=800&q=80",
  noodles:
    "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
  dumplings:
    "https://images.unsplash.com/photo-1496116218417-1a781b67dfbb?w=800&q=80",
  biryani:
    "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=800&q=80",
  dal: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
  curry:
    "https://images.unsplash.com/photo-1455619452474-d660be698907?w=800&q=80",
  hoppers:
    "https://images.unsplash.com/photo-1601050690597-df0565f6865c?w=800&q=80",
  kottu:
    "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80",
};

export const FALLBACK_RECIPES: Recipe[] = [
  {
    id: "cn-fried-rice",
    name: "Yangzhou Fried Rice",
    cuisine: "chinese",
    image: IMG.noodles,
    description: "Classic wok-fried rice with egg, shrimp, and vegetables.",
    cookingTimeMinutes: 25,
    difficulty: "easy",
    servings: 4,
    isVegetarian: false,
    spicyLevel: 1,
    ingredients: [
      { name: "cooked jasmine rice", amount: "3 cups" },
      { name: "eggs", amount: "2" },
      { name: "shrimp", amount: "150g" },
      { name: "peas and carrots", amount: "1 cup" },
      { name: "soy sauce", amount: "2 tbsp" },
      { name: "sesame oil", amount: "1 tsp" },
      { name: "green onions", amount: "3 stalks" },
    ],
    steps: [
      { order: 1, instruction: "Beat eggs and scramble in a hot wok until just set. Remove." },
      { order: 2, instruction: "Stir-fry shrimp until pink, then add vegetables for 2 minutes." },
      { order: 3, instruction: "Add cold rice, breaking clumps. Toss on high heat for 3 minutes." },
      { order: 4, instruction: "Return eggs, add soy sauce and sesame oil. Toss evenly.", timerMinutes: 2 },
      { order: 5, instruction: "Garnish with green onions and serve immediately." },
    ],
  },
  {
    id: "cn-kung-pao",
    name: "Kung Pao Chicken",
    cuisine: "chinese",
    image: IMG.chinese,
    description: "Spicy Sichuan stir-fry with peanuts and dried chilies.",
    cookingTimeMinutes: 35,
    difficulty: "medium",
    servings: 4,
    isVegetarian: false,
    spicyLevel: 3,
    ingredients: [
      { name: "chicken thigh", amount: "500g diced" },
      { name: "roasted peanuts", amount: "1/2 cup" },
      { name: "dried red chilies", amount: "8" },
      { name: "soy sauce", amount: "2 tbsp" },
      { name: "rice vinegar", amount: "1 tbsp" },
      { name: "sugar", amount: "1 tsp" },
      { name: "cornstarch", amount: "1 tbsp" },
      { name: "ginger and garlic", amount: "1 tbsp each" },
    ],
    steps: [
      { order: 1, instruction: "Marinate chicken with soy sauce and cornstarch for 15 minutes.", timerMinutes: 15 },
      { order: 2, instruction: "Mix sauce: soy, vinegar, sugar, and a splash of water." },
      { order: 3, instruction: "Fry dried chilies and Sichuan pepper until fragrant, add ginger and garlic." },
      { order: 4, instruction: "Stir-fry chicken until golden. Pour in sauce and toss.", timerMinutes: 5 },
      { order: 5, instruction: "Add peanuts, toss 1 minute, and serve with steamed rice." },
    ],
  },
  {
    id: "cn-dumplings",
    name: "Pork & Chive Dumplings",
    cuisine: "chinese",
    image: IMG.dumplings,
    description: "Homestyle jiaozi with juicy filling and crispy bottoms.",
    cookingTimeMinutes: 60,
    difficulty: "hard",
    servings: 6,
    isVegetarian: false,
    spicyLevel: 0,
    ingredients: [
      { name: "dumpling wrappers", amount: "40" },
      { name: "ground pork", amount: "400g" },
      { name: "Chinese chives", amount: "1 cup chopped" },
      { name: "ginger", amount: "1 tbsp minced" },
      { name: "soy sauce", amount: "2 tbsp" },
      { name: "sesame oil", amount: "1 tsp" },
      { name: "black vinegar", amount: "for dipping" },
    ],
    steps: [
      { order: 1, instruction: "Mix pork, chives, ginger, soy sauce, and sesame oil until sticky." },
      { order: 2, instruction: "Place 1 tbsp filling per wrapper, pleat edges tightly." },
      { order: 3, instruction: "Pan-fry dumplings in oil until bottoms are golden brown.", timerMinutes: 4 },
      { order: 4, instruction: "Add 1/2 cup water, cover and steam until cooked through.", timerMinutes: 8 },
      { order: 5, instruction: "Serve with black vinegar and chili oil." },
    ],
  },
  {
    id: "in-butter-chicken",
    name: "Butter Chicken",
    cuisine: "indian",
    image: IMG.indian,
    description: "Creamy tomato-based curry with tender tandoori-style chicken.",
    cookingTimeMinutes: 50,
    difficulty: "medium",
    servings: 4,
    isVegetarian: false,
    spicyLevel: 2,
    ingredients: [
      { name: "chicken thighs", amount: "600g" },
      { name: "yogurt", amount: "1/2 cup" },
      { name: "garam masala", amount: "2 tsp" },
      { name: "tomato puree", amount: "400g" },
      { name: "heavy cream", amount: "1/2 cup" },
      { name: "butter", amount: "3 tbsp" },
      { name: "onion", amount: "1 large" },
      { name: "ginger-garlic paste", amount: "2 tbsp" },
    ],
    steps: [
      { order: 1, instruction: "Marinate chicken in yogurt and half the garam masala for 30 minutes.", timerMinutes: 30 },
      { order: 2, instruction: "Grill or pan-sear chicken until charred. Set aside." },
      { order: 3, instruction: "Sauté onion in butter, add ginger-garlic and tomato puree. Simmer 15 minutes.", timerMinutes: 15 },
      { order: 4, instruction: "Blend sauce smooth, return to pan with cream and remaining masala." },
      { order: 5, instruction: "Add chicken, simmer 10 minutes. Finish with butter.", timerMinutes: 10 },
    ],
  },
  {
    id: "in-dal-tadka",
    name: "Dal Tadka",
    cuisine: "indian",
    image: IMG.dal,
    description: "Smoky tempered lentils — a comforting vegetarian staple.",
    cookingTimeMinutes: 40,
    difficulty: "easy",
    servings: 4,
    isVegetarian: true,
    spicyLevel: 2,
    ingredients: [
      { name: "yellow lentils (toor dal)", amount: "1 cup" },
      { name: "turmeric", amount: "1/2 tsp" },
      { name: "cumin seeds", amount: "1 tsp" },
      { name: "ghee", amount: "2 tbsp" },
      { name: "onion", amount: "1 medium sliced" },
      { name: "tomato", amount: "1 chopped" },
      { name: "green chili", amount: "2" },
      { name: "cilantro", amount: "for garnish" },
    ],
    steps: [
      { order: 1, instruction: "Pressure cook dal with turmeric until soft, about 20 minutes.", timerMinutes: 20 },
      { order: 2, instruction: "Mash dal lightly and adjust consistency with water." },
      { order: 3, instruction: "Heat ghee, add cumin until it crackles. Add onion and chili.", timerMinutes: 5 },
      { order: 4, instruction: "Add tomato, cook until soft. Pour tadka over dal." },
      { order: 5, instruction: "Garnish with cilantro and serve with rice or roti." },
    ],
  },
  {
    id: "in-veg-biryani",
    name: "Vegetable Biryani",
    cuisine: "indian",
    image: IMG.biryani,
    description: "Fragrant layered rice with spiced vegetables and saffron.",
    cookingTimeMinutes: 55,
    difficulty: "hard",
    servings: 6,
    isVegetarian: true,
    spicyLevel: 2,
    ingredients: [
      { name: "basmati rice", amount: "2 cups" },
      { name: "mixed vegetables", amount: "3 cups" },
      { name: "biryani masala", amount: "2 tbsp" },
      { name: "yogurt", amount: "1/2 cup" },
      { name: "fried onions", amount: "1 cup" },
      { name: "saffron milk", amount: "3 tbsp" },
      { name: "mint and cilantro", amount: "1/2 cup each" },
      { name: "ghee", amount: "3 tbsp" },
    ],
    steps: [
      { order: 1, instruction: "Parboil rice with whole spices until 70% cooked. Drain.", timerMinutes: 10 },
      { order: 2, instruction: "Cook vegetables with biryani masala and yogurt until tender.", timerMinutes: 15 },
      { order: 3, instruction: "Layer rice and vegetables in a heavy pot with herbs and fried onions." },
      { order: 4, instruction: "Drizzle saffron milk and ghee. Dum cook on low heat 25 minutes.", timerMinutes: 25 },
      { order: 5, instruction: "Rest 10 minutes, gently mix, and serve with raita.", timerMinutes: 10 },
    ],
  },
  {
    id: "lk-chicken-curry",
    name: "Sri Lankan Chicken Curry",
    cuisine: "sri-lankan",
    image: IMG.curry,
    description: "Dark roasted curry with coconut milk and bold spices.",
    cookingTimeMinutes: 45,
    difficulty: "medium",
    servings: 4,
    isVegetarian: false,
    spicyLevel: 3,
    ingredients: [
      { name: "chicken pieces", amount: "1 kg" },
      { name: "Sri Lankan curry powder", amount: "2 tbsp" },
      { name: "coconut milk", amount: "400ml" },
      { name: "pandan leaf", amount: "1" },
      { name: "cinnamon stick", amount: "1" },
      { name: "onion", amount: "2 sliced" },
      { name: "garlic", amount: "6 cloves" },
      { name: "goraka or lime", amount: "1 piece" },
    ],
    steps: [
      { order: 1, instruction: "Dry-roast curry powder with onion until deeply fragrant.", timerMinutes: 8 },
      { order: 2, instruction: "Add chicken and brown well on all sides." },
      { order: 3, instruction: "Pour thin coconut milk, add pandan and cinnamon. Simmer covered.", timerMinutes: 20 },
      { order: 4, instruction: "Add thick coconut milk and goraka. Simmer until sauce thickens.", timerMinutes: 12 },
      { order: 5, instruction: "Adjust salt and serve with rice and pol sambol." },
    ],
  },
  {
    id: "lk-fish-ambul-thiyal",
    name: "Fish Ambul Thiyal",
    cuisine: "sri-lankan",
    image: IMG.sriLankan,
    description: "Sour black pepper fish curry from the southern coast.",
    cookingTimeMinutes: 40,
    difficulty: "medium",
    servings: 4,
    isVegetarian: false,
    spicyLevel: 2,
    ingredients: [
      { name: "tuna steaks", amount: "600g" },
      { name: "goraka", amount: "3 pieces soaked" },
      { name: "black pepper", amount: "1 tbsp crushed" },
      { name: "curry leaves", amount: "2 sprigs" },
      { name: "turmeric", amount: "1 tsp" },
      { name: "chili powder", amount: "1 tsp" },
      { name: "water", amount: "1 cup" },
    ],
    steps: [
      { order: 1, instruction: "Rub fish with turmeric and salt. Set aside 10 minutes.", timerMinutes: 10 },
      { order: 2, instruction: "Simmer goraka, pepper, chili, and water to a thick paste.", timerMinutes: 10 },
      { order: 3, instruction: "Add fish and curry leaves. Cook gently without stirring much.", timerMinutes: 15 },
      { order: 4, instruction: "Reduce until gravy coats fish and oil separates slightly.", timerMinutes: 8 },
      { order: 5, instruction: "Serve at room temperature with rice — flavors deepen as it rests." },
    ],
  },
  {
    id: "lk-egg-hoppers",
    name: "Egg Hoppers",
    cuisine: "sri-lankan",
    image: IMG.hoppers,
    description: "Crispy bowl-shaped crepes with a soft egg center.",
    cookingTimeMinutes: 90,
    difficulty: "hard",
    servings: 4,
    isVegetarian: true,
    spicyLevel: 0,
    ingredients: [
      { name: "rice flour", amount: "2 cups" },
      { name: "coconut milk", amount: "1 cup" },
      { name: "yeast", amount: "1/2 tsp" },
      { name: "sugar", amount: "1 tsp" },
      { name: "salt", amount: "1 tsp" },
      { name: "eggs", amount: "4" },
      { name: "coconut oil", amount: "for pan" },
    ],
    steps: [
      { order: 1, instruction: "Ferment batter with yeast, sugar, and warm coconut milk for 4 hours.", timerMinutes: 240 },
      { order: 2, instruction: "Heat hopper pan (or small wok) with a drop of oil." },
      { order: 3, instruction: "Swirl thin batter to coat sides. Crack egg in center.", timerMinutes: 3 },
      { order: 4, instruction: "Cover and cook until edges are crisp and egg is set.", timerMinutes: 4 },
      { order: 5, instruction: "Serve hot with lunu miris or seeni sambol." },
    ],
  },
];

export function getFallbackRecipeById(id: string): Recipe | undefined {
  return FALLBACK_RECIPES.find((r) => r.id === id);
}
